#!/usr/bin/env python3
"""
Convert MarchReviewPass1 (OpenAI Codex / gpt-5.2 review) to BookML zip.

Chapter XMLs already exist in MarchReviewPass1/bookml/ (generated by OpenClaw).
Meta + notes come from MarchReviewPass1/unpacked/ (same md/txt format as Mayfly-unpacked).

Output: testdata/MayflyDraft2OpenAICodex.bookml.zip
"""

import os
import re
import zipfile

INPUT_DIR    = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'MarchReviewPass1')
BOOKML_DIR   = os.path.join(INPUT_DIR, 'bookml')
UNPACKED_DIR = os.path.join(INPUT_DIR, 'unpacked')
OUTPUT_ZIP   = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'MayflyDraft2OpenAICodex.bookml.zip')

NAMESPACE    = 'https://bookml.org/ns/1.0'
BOOK_ID      = 'mayfly-mutiny'
BOOK_TITLE   = 'Mayfly Mutiny'
DRAFT        = 3
BASED_ON     = 2
NUM_CHAPTERS = 12

DRAFT_CREATED  = '2026-03-10T07:39:39+01:00'
DRAFT_DATE     = '2026-03-10'
DRAFT_MODIFIED = '2026-03-11'

# The chapter XMLs from OpenClaw were stamped draft=2; patch them to draft=3 on the fly.
_CHAPTER_DRAFT_ATTR_RE    = re.compile(r'(<chapter\b[^>]*\s)draft="2"')
_PARA_DRAFT_MODIFIED_RE   = re.compile(r'draft-modified="2"')


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def xe(text):
    """XML-escape a string."""
    return (text
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;'))


def ch_id(n):
    return f'ch{n:02d}'


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

_META_RE = re.compile(r'^\[\[([A-Z0-9\-]+)\]\]\s+Topic:\s+(.+?)\s*$', re.IGNORECASE)
_NOTE_RE = re.compile(r'^([A-Z0-9\-]+)\|\[(\w+)\]\s+(.+?)\s*$')
_PID_RE  = re.compile(r'<para\s+pid="([^"]+)"')


def extract_pids_from_chapter_xml(xml_text):
    """Return ordered list of pids from a chapter XML."""
    return _PID_RE.findall(xml_text)


def parse_meta(path):
    """Return {pid: topic_text} ordered by file appearance."""
    meta = {}
    if not os.path.isfile(path):
        return meta
    with open(path, encoding='utf-8-sig') as f:
        for line in f:
            m = _META_RE.match(line.rstrip('\r\n'))
            if m:
                meta[m.group(1)] = m.group(2)
    return meta


def parse_notes(path):
    """Return {pid: (note_type, note_text)} ordered by file appearance."""
    notes = {}
    if not os.path.isfile(path):
        return notes
    with open(path, encoding='utf-8-sig') as f:
        for line in f:
            m = _NOTE_RE.match(line.rstrip('\r\n'))
            if m:
                notes[m.group(1)] = (m.group(2), m.group(3))
    return notes


# ---------------------------------------------------------------------------
# XML generators
# ---------------------------------------------------------------------------

def meta_xml(n, pids, meta_data):
    cid = ch_id(n)

    # Emit in chapter order first, then any pids that exist only in meta (orphaned)
    pid_set = set(pids)
    ordered = [(pid, meta_data[pid]) for pid in pids if pid in meta_data]
    for pid, topic in meta_data.items():
        if pid not in pid_set:
            ordered.append((pid, topic))

    if not ordered:
        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<meta xmlns="{NAMESPACE}"'
            f' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'
            f' xsi:schemaLocation="{NAMESPACE} ../schema/bookml-meta.xsd"'
            f' bookml-version="1.0" chapter-id="{cid}"'
            f' book-id="{BOOK_ID}" draft="{DRAFT}"/>'
        )

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<meta xmlns="{NAMESPACE}"',
        f'      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
        f'      xsi:schemaLocation="{NAMESPACE} ../schema/bookml-meta.xsd"',
        f'      bookml-version="1.0"',
        f'      chapter-id="{cid}"',
        f'      book-id="{BOOK_ID}"',
        f'      draft="{DRAFT}">',
    ]
    for pid, topic in ordered:
        lines.append(f'  <para-meta pid="{pid}">')
        lines.append(f'    <topic>{xe(topic)}</topic>')
        lines.append('  </para-meta>')
    lines.append('</meta>')
    return '\n'.join(lines)


def notes_xml(n, pids, notes_data):
    cid = ch_id(n)

    pid_set = set(pids)
    ordered = [(pid, notes_data[pid]) for pid in pids if pid in notes_data]
    for pid, note in notes_data.items():
        if pid not in pid_set:
            ordered.append((pid, note))

    if not ordered:
        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<notes xmlns="{NAMESPACE}"'
            f' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'
            f' xsi:schemaLocation="{NAMESPACE} ../schema/bookml-notes.xsd"'
            f' bookml-version="1.0" chapter-id="{cid}"'
            f' book-id="{BOOK_ID}" draft="{DRAFT}"/>'
        )

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<notes xmlns="{NAMESPACE}"',
        f'       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
        f'       xsi:schemaLocation="{NAMESPACE} ../schema/bookml-notes.xsd"',
        f'       bookml-version="1.0"',
        f'       chapter-id="{cid}"',
        f'       book-id="{BOOK_ID}"',
        f'       draft="{DRAFT}">',
    ]
    for pid, (note_type, note_text) in ordered:
        note_id = f'{pid}-N001'
        lines.append(f'  <para-notes pid="{pid}">')
        lines.append(
            f'    <note id="{note_id}" type="{xe(note_type)}"'
            f' author-type="human" draft="{DRAFT}">'
        )
        lines.append(f'      <body>{xe(note_text)}</body>')
        lines.append('    </note>')
        lines.append('  </para-notes>')
    lines.append('</notes>')
    return '\n'.join(lines)


def book_xml():
    components = []
    for n in range(1, NUM_CHAPTERS + 1):
        cid = ch_id(n)
        seq = n * 1000
        components.append(
            f'      <component id="{cid}" type="chapter" seq="{seq}"\n'
            f'                 chapter-file="{cid}/{cid}-chapter.xml"\n'
            f'                 meta-file="{cid}/{cid}-meta.xml"\n'
            f'                 notes-file="{cid}/{cid}-notes.xml"\n'
            f'                 title="Chapter {n}"\n'
            f'                 draft="{DRAFT}"/>'
        )

    return '\n'.join([
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<book xmlns="{NAMESPACE}"',
        f'      bookml-version="1.0"',
        f'      id="{BOOK_ID}"',
        f'      xml:lang="en">',
        '  <bookinfo>',
        f'    <title>{xe(BOOK_TITLE)}</title>',
        '    <author role="author">',
        '      <surname>Unknown</surname>',
        '    </author>',
        '    <genre>fiction</genre>',
        '    <language>en</language>',
        '    <versioning>',
        f'      <draft number="{DRAFT}" status="in-progress"',
        f'             created="{DRAFT_CREATED}"',
        f'             based-on="{BASED_ON}"',
        f'             author-type="ai"',
        f'             author="OpenAI gpt-5.2 via Openclaw (MarchReviewPass1)"',
        f'             label="MarchReviewPass1 OpenAI Codex revision (draft 3)"/>',
        '    </versioning>',
        f'    <created>{DRAFT_DATE}</created>',
        f'    <modified>{DRAFT_MODIFIED}</modified>',
        '  </bookinfo>',
        '  <contents>',
        '    <bodymatter>',
        '\n'.join(components),
        '    </bodymatter>',
        '  </contents>',
        '</book>',
    ])


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    with zipfile.ZipFile(OUTPUT_ZIP, 'w', zipfile.ZIP_DEFLATED) as zf:

        # book.xml
        zf.writestr('book.xml', book_xml().encode('utf-8'))
        print('[+] book.xml')

        for n in range(1, NUM_CHAPTERS + 1):
            cid = ch_id(n)

            chapter_xml_path = os.path.join(BOOKML_DIR, cid, f'{cid}-chapter.xml')
            meta_path        = os.path.join(UNPACKED_DIR, f'{cid}_chapter-{n}_meta.md')
            notes_path       = os.path.join(UNPACKED_DIR, f'{cid}_chapter-{n}_notes.txt')

            # Read pre-built chapter XML and patch draft number from 2 -> 3
            with open(chapter_xml_path, encoding='utf-8') as f:
                ch_xml_text = f.read()
            ch_xml_text = _CHAPTER_DRAFT_ATTR_RE.sub(r'\g<1>draft="3"', ch_xml_text)
            ch_xml_text = _PARA_DRAFT_MODIFIED_RE.sub('draft-modified="3"', ch_xml_text)

            pids       = extract_pids_from_chapter_xml(ch_xml_text)
            meta_data  = parse_meta(meta_path)
            notes_data = parse_notes(notes_path)

            mt_xml = meta_xml(n, pids, meta_data)
            nt_xml = notes_xml(n, pids, notes_data)

            zf.writestr(f'{cid}/{cid}-chapter.xml', ch_xml_text.encode('utf-8'))
            zf.writestr(f'{cid}/{cid}-meta.xml',    mt_xml.encode('utf-8'))
            zf.writestr(f'{cid}/{cid}-notes.xml',   nt_xml.encode('utf-8'))

            print(f'[+] {cid}: {len(pids)} paras, {len(meta_data)} meta entries, {len(notes_data)} notes')

    print(f'\nDone: {OUTPUT_ZIP}')

    with zipfile.ZipFile(OUTPUT_ZIP, 'r') as zf:
        names = sorted(zf.namelist())
    print(f'Zip contains {len(names)} files.')


if __name__ == '__main__':
    main()
